# Generated by Django 4.1.1 on 2022-10-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=255)),
                ('tlf', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=255)),
                ('prezioa', models.FloatField()),
                ('alokatzeData', models.CharField(max_length=255)),
                ('alokatzailea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kotxeak.pertsona')),
            ],
        ),
    ]
