# Generated by Django 4.1.1 on 2022-10-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotxea',
            name='alokatzeData',
            field=models.DateField(null=True),
        ),
    ]
