# Generated by Django 4.1.1 on 2022-10-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0002_alter_kotxea_alokatzedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotxea',
            name='alokatzailea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotxeak.pertsona'),
        ),
        migrations.AlterField(
            model_name='kotxea',
            name='alokatzeData',
            field=models.DateField(),
        ),
    ]
