# Generated by Django 4.1.1 on 2022-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0003_alter_kotxea_alokatzailea_alter_kotxea_alokatzedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotxea',
            name='alokatzailea',
        ),
        migrations.RemoveField(
            model_name='kotxea',
            name='alokatzeData',
        ),
    ]
