# Generated by Django 4.1.1 on 2022-10-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotxeak', '0004_remove_kotxea_alokatzailea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alokairua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alokatuData', models.DateField()),
                ('aamaieraData', models.DateField()),
                ('alokatzailea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kotxeak.pertsona')),
                ('kotxea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kotxeak.kotxea')),
            ],
        ),
    ]
